# Generated by Django 6.0.2 on 2026-02-15 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('marque', models.CharField(choices=[('ferrari', 'Ferrari'), ('lamborghini', 'Lamborghini'), ('porsche', 'Porsche'), ('mclaren', 'McLaren'), ('bentley', 'Bentley'), ('aston_martin', 'Aston Martin'), ('rolls_royce', 'Rolls-Royce'), ('other', 'Autre')], max_length=50)),
                ('modele', models.CharField(max_length=120)),
                ('annee', models.PositiveIntegerField()),
                ('kilometrage', models.PositiveIntegerField(help_text='En km')),
                ('prix', models.DecimalField(decimal_places=0, max_digits=12)),
                ('puissance_ch', models.PositiveIntegerField(blank=True, null=True, verbose_name='Puissance (ch)')),
                ('moteur', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='vehicules/')),
                ('en_vedette', models.BooleanField(default=False)),
                ('ordre_affichage', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['-ordre_affichage', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicules/galerie/')),
                ('legende', models.CharField(blank=True, max_length=120)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.vehicule')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
