# Generated by Django 6.0.2 on 2026-02-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='image_url',
            field=models.URLField(blank=True, help_text='Image depuis internet si pas de fichier uploadé.', max_length=500, verbose_name='URL image (externe)'),
        ),
    ]
